version: "3.8"
services: 
  nginx: 
    container_name: nginx_1
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - front-end 

  front-end: 
    container_name: front_end_api
    build: ./front_end_api
    depends_on: 
    - pilot_api
    - tier_api
    # - service_4 

  pilot_api: 
    container_name: pilot_api
    build: ./pilot_api


  tier_api:
    container_name: tier_api 
    build: ./tier_api


  # service_4:
  #   container_name: service_4
  #   build: ./service_4