---
# tasks file for dockerinstall
- name: Installing dependencies for docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: latest
    update_cache: true

- name: Adding gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker engine
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: true
    state: latest

# - name: "Add jenkins to docker group"
#   user:
#     name: jenkins
#     groups: docker
#     append: yes

- name: Install docker via pip
  pip:
    name: docker