all:
  children:
    nginx:
      hosts:
        load-balancer:
    swarm_managers:
      hosts:
        swarm-manager:
    swarm_workers:
      hosts:
        swarm-worker:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    # ansible_user: jenkins
    # ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    # ansible_python_interpreter: "/usr/bin/python3"