---
# tasks file for swarm-manager
- name: Init swarm
  docker_swarm:
    state: present
  register: swarm_info
  
# - name: Deploy app
#   docker_stack:
#     state: present
#     name: event_generator
#     compose:
#       - /home/jenkins/docker-compose.yaml